#!/bin/bash
SUCCESS=0
FAILURE=1

#
# This script performs a simple functional test agaist the locally deployed application
# The port number can be passed as a parameter, if null the port 80 is used.
#
echo "--> Testing the product list functionality"
result=$(curl -s http://localhost:${1:-80}/prodcatalog/)
if [[ $result =~ "Product Catalog" ]]; then
    echo "Passed."
else
    echo "Functional tests failed for the web content: $result"
    echo $result
    exit $FAILURE
fi

echo "--> Testing the product page functionality"
result=$(curl -s http://localhost:${1:-80}/prodcatalog/product?id=-1)
if [[ $result =~ "Product Details" ]]; then
    echo "Passed."
else
    echo "Functional tests failed for the web content: $result"
    echo $result
    exit $FAILURE
fi

exit $SUCCESS