#!/bin/bash
cd /home/ec2-user/javaapp
wget https://d1f28333hybq4l.cloudfront.net/apache-tomcat-9.0.38.tar.gz
mkdir /opt/tomcat
tar xvf apache-tomcat-9*tar.gz -C /opt/tomcat --strip-components=1
cd /opt/tomcat
sed -i 's|port="8080"|port="80"|g' conf/server.xml
mv /home/ec2-user/javaapp/prodcatalog.war webapps/
yum -y install java