version: 0.2

phases:
  pre_build:
    commands:
      - mvn clean compile test
  build:
    commands:
      - mvn package -Dmaven.test.skip=true
artifacts:
  type: zip
  files:
    - 'appspec.yml'
    - 'template.yml'
    - 'scripts/*'
    - 'target/ROOT.war'
    - 'template-configuration.json'
